### ISSUE TITLE
application terminates after login, under Ubuntu 22.10 and android 11

### ISSUE THREAD

**Issue by rollefko** [littlejo/huawei-lte-examples#13]
```
rolle@rolle-MS-7C37:~/Schreibtisch/huawei-lte-examples/huawei-lte-band$ python3 main.py
[WARNING] [Config      ] Older configuration version detected (0 instead of 21)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/rolle/.kivy/logs/kivy_23-02-08_0.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/usr/lib/python3/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 525.78.01'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1080/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_xclip', 'clipboard_xsel', 'clipboard_dbusklipper'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
xclip - FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'xclip'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(
  File "/usr/lib/python3/dist-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

xsel - FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'xsel'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(
  File "/usr/lib/python3/dist-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/home/rolle/Schreibtisch/huawei-lte-examples/huawei-lte-band/main.py", line 187, in <module>
     LoginApp().run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 746, in mainloop
     self._mainloop()
   File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 478, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python3/dist-packages/kivy/base.py", line 339, in idle
     Clock.tick()
   File "/usr/lib/python3/dist-packages/kivy/clock.py", line 591, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/home/rolle/Schreibtisch/huawei-lte-examples/huawei-lte-band/main.py", line 119, in set_label
     info = huawei_lte.get_all_monitor_information()
   File "/home/rolle/Schreibtisch/huawei-lte-examples/huawei-lte-band/huawei_lte_lib.py", line 93, in get_all_monitor_information
     'rsrq': get_signal_int(signal_info['rsrq']),
   File "/home/rolle/Schreibtisch/huawei-lte-examples/huawei-lte-band/huawei_lte_lib.py", line 10, in get_signal_int
     return int(value.split('d')[0])
 ValueError: invalid literal for int() with base 10: '-3.0'
rolle@rolle-MS-7C37:~/Schreibtisch/huawei-lte-examples/huawei-lte-band$ 
```
-3.0 is the RSRQ value shown in the router

**Comment by inspiredearth** [comment]
It's 10  months later, and the same issue occurring for me. As you posted this in Feb, and there's been no reply, it seems safe t say the developer has moved on from this project. If you found or find other solutions for managing the bands, etc., on Huawei routers, please let me know.

**Comment by rollefko** [comment]
https://www.ltehmonitor.com/en/

look under "Radio configuration"
mark the bands you want to use und save.
i used the huawei b535-323 and sometimes he forgot the selection.

now i use a zyxel lte5398-m904 with a FTS Complete MAX LTE MIMO XPOL antenne.
